### ISSUE TITLE
Makefile template could use latexmk

### ISSUE THREAD

**Issue by timj** [ivoa-std/ivoatex#10]
At the IVOA session today we discussed the problem of the standards documents not building sufficient times to sort out references.  I think that latexmk is part of texlive so should be available to everyone that uses latex these days (unless they have a minimal subset). MacTex for example comes with it and it looks like ubuntu includes it with texlive-bibtex-extra.

**Comment by msdemlei** [comment]
PR #12 would address this.

**Comment by msdemlei** [comment]
Since PR #12 is merged, I'd say this should be fixed.  Please re-open if I'm wrong there.
