### ISSUE TITLE
Patch out german TeX emulation from our tth

### ISSUE THREAD

**Issue by msdemlei** [ivoa-std/ivoatex#110]
Since its version 2.0, tth tries to interpret the ancient German TeX
sequences with the double quote as an active character ("`, "', "a, "s,
etc).  In our context, that is nothing but trouble.  We should probably
patch that out or perhaps get an upstream option to switch it off.

[all the while: Don't have ASCII double quotes in running text.  Use ``
'' instead.  It's of course ok to have them in \verb and listing
environments]

**Comment by mbtaylor** [comment]
Good work tracking down the reason for this, it would certainly be good to stop it doing that; this has showed up in numerous IVOA documents.

**Comment by msdemlei** [comment]
Fixed (or so I hope) by PR #111
