### ISSUE TITLE
Makefile template should contain a reminder (or do it) to get the submodule

### ISSUE THREAD

**Issue by teuben** [ivoa-std/ivoatex#27]
As is, any poor soul will see that include ivoatex/Makefile fails to load.... Could the template contain the solution, e.g. a comment line

         #   git clone --recurse-submodules https://github.com/ivoa-std/ivoatex

But this requires somebody to read the Makefile. And who does?

Even better, you could change the tail end of the template to:

      -include ivoatex/Makefile
      ivoatex/Makefile:
              git clone --recurse-submodules https://github.com/ivoa-std/ivoatex

this way the "make" command would make the pdf, downloading the rrequired.

**Comment by msdemlei** [comment]
On Thu, Nov 19, 2020 at 07:14:44AM -0800, Peter Teuben wrote:
> As is, any poor soul will see that include ivoatex/Makefile fails
> to load.... Could the template contain the solution, e.g. a comment

Yeah... I still with git had something as simple and straightforward
as svn:externals (where this comes from).

> line
> 
> #   git clone --recurse-submodules https://github.com/ivoa-std/ivoatex
> 
> But this requires somebody to read the Makefile. And who does?
> 
> Even better, you could change the tail end of the template to:
> 
> -include ivoatex/Makefile
> ivoatex/Makefile:
>         git clone --recurse-submodules https://github.com/ivoa-std/ivoatex
> 
> this way the "make" command would make the pdf, downloading the rrequired.

Call me conservative, but I still think something like "make"
should preferably not connect to remote services, in particular not
ones people may object to (which certainly includes github).  People
should at least not experience oddities when they use ivoatex on
their own git instances.

I'd much rather have some sequence of git submodule incantations
that:

(a) do the initial checkout when folks forget the recurse-submodules
when cloning.

(b) do a reliable update of the submodule to the latest commit on
ivoatex's master branch (from whereever it was checked out).

I've never found the patience to work that out from
git-submodule's documentation -- but perhaps someone else has.  I'd
be very grateful for contributions.

**Comment by teuben** [comment]
the astropy community also uses this technique, maybe they have a suggestion (i'll have a look at some point).

But my point remains: you need to be a git expert to realize that this needs to be done. I don't always remember the incantation, so at least a comment would be useful.
I ran into this while doing "git clone https://github.com/mmpcn/slapvamdc"  but had I done/remembered 'git clone --recurse-submodules https://github.com/mmpcn/slapvamdc' it would not have caused make to fail.

**Comment by msdemlei** [comment]
I hope this should be addressed with PR #36.
