### ISSUE TITLE
submission.py should be fixed

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/ivoatex#3]
I've SVN-committed an updated version of `submission.py`, which works with python3 (it is currently broken). Can you update it from there or shall I do a PR?

**Comment by BaptisteCecconi** [comment]
I've issued a PR from my local fork.

**Comment by BaptisteCecconi** [comment]
Who is supposed to merge this PR? :-) (@msdemlei ?)

**Comment by msdemlei** [comment]
On Fri, Oct 25, 2019 at 05:57:09AM -0700, Baptiste Cecconi wrote:
> Who is supposed to merge this PR? :-) (@msdemlei ?) 

Very frankly, anything that has to do with github processes I don't
really feel qualified to judge on, and anyway I'm a bit reluctant to
do, in effect, technical support for Microsoft.

Hence, I'd much prefer if ivoatex on github could, for now, be
maintained by the ivoa-github team (Pat? James? Anyone else?).  Once
things have shaken out, it should be rather straightforward to merge
changes either way -- where, true, at this point I expect ivoatex on
github will become "trunk", so whatever changes I still apply on
volute would be merged into github ivoatex.

So, whoever can and agrees with the PR (personally, I'd vote for
CC-0, but for what little text we produce it probably doesn't matter
mucht): Totally feel free to merge.

**Comment by BaptisteCecconi** [comment]
This PR is not about licensing but about the submission.py script, which is broken in python3. I fixed it but I cannot merge it, since I’m not maintainer of the repository. I could commit it on volute if it helps, but we need to find a way to have consistent software on github since this is the new platform we use. 

Cheers 
Baptiste

**Comment by msdemlei** [comment]
Ah.  True -- I've merged the PR (commit 48a0391f63bc9faf50d92f55c5c6879b5355c1b9) and propagated your changes to ivoatex-volute as well.

Thanks!
