### ISSUE TITLE
Include CC-BY-SA-4.0 license automatically ?

### ISSUE THREAD

**Issue by BaptisteCecconi** [ivoa-std/ivoatex#5]
On [that discussion](https://github.com/github/choosealicense.com/issues/33#issuecomment-271960620) I found the following code which could used to automatically include the LICENSE file in our repositories.

```
curl https://creativecommons.org/licenses/by-sa/4.0/legalcode.txt > LICENSE &&
  git add LICENSE && git commit --amend --no-edit && git push -f
```

**Comment by olebole** [comment]
Maybe put that in the [ivoa-std/volute-migration](https://github.com/ivoa-std/volute-migration) script?

**Comment by BaptisteCecconi** [comment]
I have no idea, I just copy-pasted from the web page linked in my message. I don't pkan to include this myself (I have no idea on how to do it), I'm just trying to help.
