### ISSUE TITLE
make doesn't automatically generate role_diagram pdf from source

### ISSUE THREAD

**Issue by pdowler** [ivoa-std/ivoatex#9]
In DataLink, The Makefile has 
`SOURCES = $(DOCNAME).tex role_diagram.pdf`
If I remove role_diagram.pdf and role_diagram.svg they can be regenerated with
`make role_diagram.pdf`
but a regular build like:
`make biblio forcetex `
does not generate them (from role_diagram.xml) automatically. Should it? Or should I really do
`make role_diagram.pdf  biblio forcetex`

**Comment by msdemlei** [comment]
On Tue, Feb 18, 2020 at 11:57:21AM -0800, Patrick Dowler wrote:
> In DataLink, The Makefile has 
> `SOURCES = $(DOCNAME).tex role_diagram.pdf`
> If I remove role_diagram.pdf and role_diagram.svg they can be regenerated with
> `make role_diagram.pdf`
> but a regular build like:
> `make biblio forcetex `
> does not generate them (from role_diagram.xml) automatically. Should it? Or should I really do
> `make role_diagram.pdf  biblio forcetex`

Yeah -- forcetex doesn't use the dependencies, and thus they're not
built.  That's arguably a bug.

I'd be totally open to fix this. I'm pretty sure there's a standard
way to have a "rebuild, assuming a single new dependency", which the
forcetex target is supposed to do (like make -W $(DOCNAME).tex).

If you find something, great, if not, I'd try a hack like

```
forcetex: 
  make -W $(DOCNAME).tex $(DOCNAME).pdf
```

-- though that probably has all kinds of portability issues.  Then
again, the ivoatex Makefile probably has many GNUisms already, so
perhaps that's not all that bad.

**Comment by msdemlei** [comment]
This, I believe, is addressed in PR #12.  Could you check if it works for you now?

**Comment by msdemlei** [comment]
Since PR #12 is merged now, I'd say this ought to be fixed.  Feel free to re-open if I'm wrong.
