### ISSUE TITLE
Bibliography generation fails in TeXLive 2022

### ISSUE THREAD

**Issue by nxg** [ivoa-std/ivoatex#97]
When processing a document including a bibliography, with TeXLive 2022, BibTeX fails:

    [...]
    [40] [41] (./VOUnits.bbl
    Runaway argument?
    \parindent \z@ \bibpreamble \bibfont \list {\@biblabel {\the \c@NAT@ctr \ETC.
    ! Paragraph ended before \HD@@guesstoclevel was complete.
    <to be read again> 
    \par 
    l.1 \begin{thebibliography}
                             {xx}
    ? ^D
    ! Emergency stop.

However a slightly earlier TeXLive release works OK, using

    pdflatex --version 
    pdfTeX 3.141592653-2.6-1.40.23 (TeX Live 2022/dev)
    kpathsea version 6.3.4/dev

(despite the banner, this is from TeXLive 2021).

To reproduce (I believe), this is when running `make` in `ivoa-std/VOUnits` with VOUnits repository revision 1250c9ff74d0b7484cfbb.  Running that starts

    github/VOUnits> make
    /bin/echo -n '\vcsrevision{' > gitmeta.tex
    /bin/echo -n "b10aee5" >> gitmeta.tex
    if [ ! -z "" ]; then /bin/echo -n -dirty >> gitmeta.tex; fi
    /bin/echo } >> gitmeta.tex
    /bin/echo '\vcsdate{' 2023-01-20 11:48:40 +0000 '}' >>gitmeta.tex
    latexmk -pdf VOUnits
    Rc files read:
      NONE
    Latexmk: This is Latexmk, John Collins, 17 Mar. 2022. Version 4.77, version: 4.77.
    Latexmk: applying rule 'pdflatex'...
    Rule 'pdflatex': File changes, etc:
       Changed files, or newly in use since previous run(s):
      gitmeta.tex
    Rule 'pdflatex': The following rules & subrules became out-of-date:
      pdflatex
    ------------
    Run number 1 of rule 'pdflatex'
    ------------
    ------------
    Running 'pdflatex  -recorder  "VOUnits.tex"'
    ------------
    This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022) (preloaded format=pdflatex)
     restricted \write18 enabled.
    entering extended mode
    (./VOUnits.tex
    LaTeX2e <2022-06-01> patch level 4
    L3 programming layer <2022-07-01> (ivoatex/ivoa.cls
    Document Class: ivoa 
    [... and eventually the error as above]

I'm running this on macOS, but I'd be surprised if it's sensitive to the platform.

**Comment by msdemlei** [comment]
Before I fiddle together a Debian unstable and try to trigger that myself: does VOUnits.bbl change when generated by the different BibTeX-es, and if so, how?

The \HD@@guesstoclevel macro that makes LaTeX give up, interestingly, is (probably) from the hypdoc package, which I've not been aware of so far.  In fact, according to my build log, it's not even touched by ivoatex builds in 2020.20210202-3 (i.e., Debian bullseye).

Can you see from VOUnits.log what package(s) pull in hypdoc on your new texlive?

**Comment by nxg** [comment]
It's not at all clear to me what package is including it (but `.log` files aren't always easy to read).
The [VOUnits.log](https://github.com/ivoa-std/ivoatex/files/10466944/VOUnits.log) is attached here for reference.

I notice that, when it's included, there's a warning

    Package hypdoc Warning: hyperref has been loaded before. Check the options! on 
    input line 56.

The file `VOUnits.bbl` is identical between the two versions, and the `.blg` file differs only in the reported TL version.

**Comment by msdemlei** [comment]
On Fri, Jan 20, 2023 at 06:18:25AM -0800, Norman Gray wrote:
> It's not at all clear to me what package is including it (but
> `.log` files aren't always easy to read).

Yes... this looks quite a bit like higher magic.  It seems it is
pulled in as a side effect of \begin{document}.  I confess this is a
bit beyond my level of casual TeXpertise, and hence I'm trying
upstream before plunging into the deeper guts of LaTeX and hyperref:
https://github.com/ho-tex/oberdiek/issues/91.

**Comment by nxg** [comment]
I had a thought, and checked the documentation for specifically `hypdoc`, which (it turns out) is exclusively for adding hypertex-like functions to the `doc` package which documents LaTeX source code.

But... aha!... the `ivoa.cls` file loads `doc`, and this is presumably where `hypdoc` comes in, possibly in a slightly tricky way.  But

> the doc package [is] a package to provide code documentation for TEX code. Since then it has be used all over the place to document the LATEX kernel and most of the packages that are nowadays available. 

Thus `ivoa.cls` probably _shouldn't_ be loading `doc`, and it appears that it doesn't have to.  If I comment out `\RequirePackage{doc}` from there, then `make` works fine in a checkout, with TeXLive 2022.

(Just in passing, I'll note that `fontenc` and `inputenc` might be redundant in current TL versions, since even pdflatex is unicode-by-default now.  I don't think there's too much cleverness/voodoo in those packages, but myself, I'm a great fan of minimalism in LaTeX preambles.  I could raise an issue suggesting at least experimenting with removing them)

**Comment by msdemlei** [comment]
On Mon, Jan 23, 2023 at 01:10:33AM -0800, Norman Gray wrote:
> Thus `ivoa.cls` probably _shouldn't_ be loading `doc`, and it
> appears that it doesn't have to.  If I comment out

Good point.  I can't remember that I added it, but it's been in from
the very first commit af5befb, which would suggest I inherited it
from the ancient VOTable tooling, which may have included it for
\verb or something.  I suspect there's really no point in keeping it
around.

> (Just in passing, I'll note that `fontenc` and `inputenc` might be
> redundant in current TL versions, since even pdflatex is
> unicode-by-default now.  I don't think there's too much
> cleverness/voodoo in those packages, but myself, I'm a great fan of
> minimalism in LaTeX preambles.  I could raise an issue suggesting
> at least experimenting with removing them)

Well, let me be conservative here.  Who knows what kind of ancient
LaTeX may want to process the source?  As long as I don't have a
strong reason to break them, I'd rather not.

**Comment by msdemlei** [comment]
On Mon, Jan 23, 2023 at 01:27:30PM +0100, msdemlei wrote:
> from the ancient VOTable tooling, which may have included it for
> \verb or something.  I suspect there's really no point in keeping it

Well... it turns out that the \BibTeX macro that, for instance,
ivoatexDoc uses, is declared in doc.  Ah well.  That's probably not
sufficient reason to keep it given it adds a certain amount of
fragility.

**Comment by mbtaylor** [comment]
I can easily imagine that there are parts of the original VOTable TeX source that could be unnecessary or harmful.

**Comment by nxg** [comment]
IThe `\BibTeX` macro appears to be exclusively for typesetting the BibTeX logo, and would be very easy to mock up.  `\def\BibTeX{Bib\TeX}` would be 90% of the way there (the version in `doc.sty` is basically that, plus some overfussy kerning).

I see that `doc.sty` does declare `\verb`, but only in order to override the standard one, which is otherwise probably fine.

**Comment by msdemlei** [comment]
Sure... there's https://github.com/ivoa-std/ivoatex/pull/98 proposing to drop doc.sty.  I just let it sit for a while in case anyone watching brings up a good reason why I shouldn't do it.

**Comment by nxg** [comment]
If we need to back-fill any now-missing functionality into `ivoa.cls`, I can volunteer to do so.

**Comment by msdemlei** [comment]
On Mon, Jan 23, 2023 at 07:02:19AM -0800, Norman Gray wrote:
> If we need to back-fill any now-missing functionality into
> `ivoa.cls`, I can volunteer to do so.

Thanks for the offer, but no, I don't think anything serious will
break (still: we ought to have a nice ivoatex regression test, and
I've finally started to build one).

**Comment by msdemlei** [comment]
Since we're no longer loading doc.sty as per PR #98, this bug ought to be fixed.
